version: '3.8'

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.8.0
    container_name: filebeat 
    restart: always

  rest-ingress:
    image: node:14.5-slim
    container_name: rest-ingress 
    restart: always
