version: '3.8'

volumes:
  app-volume:

services:
  spider-app:
    image: adamchandra/spider-app
    container_name: spider-app
    restart: always
    volumes:
      - app-volume:/usr/src/app
    networks:
      - watr-net
