version: '3.8'

volumes:
  rest-logs:

services:
  rest-portal:
    image: adamchandra/watr-front
    container_name: rest-portal 
    ports:
      - "3100:3100"
    restart: always
    volumes:
      - rest-logs:/usr/src/app/logs
