version: '3.8'

x-service-defaults:
  &service-defaults
  image: adamchandra/watr-front
  restart: always
  networks:
    - watr-net

x-workflow-service:
  &workflow-service
  << : *service-defaults

# command: ["portal-server"]

services:
  rest-portal:
    << : *workflow-service
    container_name: rest-portal
    ports:
      - "3100:3100"
    command: ['portal-server']

  service-hub:
    << : *workflow-service
    container_name: service-hub
    command: ["start-service", "--dockerize", "--service-name", "hub"]

  upload-ingestor:
    << : *workflow-service
    container_name: upload-ingestor
    command: ["start-service", "--dockerize", "--service-name", "upload-ingestor"]

  spider-service:
    << : *workflow-service
    image: adamchandra/spider-app
    container_name: spider-service
    command: ["start-service", "--dockerize", "--service-name", "spider"]
